env:
  global:
    - secure: nMSICCi2Voa8Z7Pz7kRj9BBqKeSzL0zyetxlR5pY0GPp8Ec7iO8BclBIQuAJ4gqIUI6oxCkF+Stn7vdTO00GnbDPzlOoNuro9HKx6xAyx4NdoPIC1t9VgfBhHw4RlHlhIq2w/IFw3AB7qaK60OUDP7NFAJNiYPyi5QltlS0Q3QKt/9dqVJnWnMO/9qDDPl8zCxB7qtEsR/nE7TwoIZCcoSAVL+hnjhfcrq1jNn+lKlZM2DJPZ5OTBcSlkVKcPAmA0MSY7WCcONy5BBZtRa7eadOP3BpYzsVG3UXqDlZmPBrzkyybNvWu2t/qpz6FKx4SNt8QyAQCcYJFSPuuVZ7jo/pAJbzD3L91b/F7DupNmO5w+MqH0txcEfdVdmLG/NCQbGiI9W2+XgeN72QBl+AoFc2eW1tldYHFbhJJl1yIJnyv0xytUCVh3spxU+nKTKvcXIl4rFboedbc37t4lfmN5LvEUUCN2jAhEXwPnOZWhEIK+7u0wotnYnMoNqcOEU+PaRCC+DVEydnNnepoR8g/qkpiMfIgv4r55R5VQzTmDlwwZEPV+jqxHbfF4KNrscn95Mlbr9FReA5AQk1s6RBRjkWKZaSSdIbp7ZRVeSXGr6MF9cNB36D8xZKPOerb/190IB7dhApnhldmh1O536XvrJJSsdOpXLR8UWsk5ytmv2M=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Risk
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
