env:
  global:
    - secure: lmuP4aePTpXFhMxXecFFdB97ws/NCpu+dt+fa3iC8J69GsEGjJgsRXcWNQSVip0lPcvHwJxwLZ+gW3P5ojlL20rNhefGKT6HM2u1f1oC5ApNNrVHWSp/pX4xQXaf+8dX85GIsfZJ+KVt/+B7XRThb9NIvpgTd3G4H4IkYS1Ilj6gTe85ad/KPaqQuHhCNQY5I/XUoo43CFrSl+ta/LLqMQJUV2z6NP4Wz9D4zMziVoCCqGVYOmT8qb9skN/nUf3jPgFbp+s+B35XLU1VdTMfgO4OrNU8EkuyCd83xmvm4U6Ova2X1olTAfkxrqJfMk7uyt8PLBCpB73VssEA71vUNEwSR+px0Pafd2Qz039Z7u0n2uenGAHq+apPgDUStCLNl2IhinUL+HLyExv1P8PWV1+CmJWVmsrNTUKQE3PScT10vu+SixivltjERserBD16rAwUKZNeaPBoFN1PDQiXq18rQuhsP0FtfZXilVwCGdQ3k6LcG+Hz5JuSXL8hE6kroTiCSz/MOtdEusRsh9uiZguGx6U8M4kk/4GlEXg3abY3HX0v1qQgCNPjDJyO+q9PFOLVaUAUW/Jpb5We8K9iBjWl59YQ8RjmastR7dfadWu+/YoRQeO0RZHzkGAknRglEf4hBfVbrNtNvc/tR/HhfIaV12gRL1pm8Hx++pZ5D+E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Risk
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
