env:
  global:
    - secure: PTlAQP8VmuBsVho4uZthfOpMVNTHaFsWz72P3exI46qXh9QvwtlQBG93yy9DfJdg6nKCTHK+c2MM7YU3M3uY+GYldnYBQBlClFZ2K0EjclU2WQqLMGEtD73KVq+MiNMRwvd6hnmPZApt16GuA8mqff7y4l2JUS+7/67yjarx6nCJJqTBkuGMWknBJ8H7HX7dD8an/KmAUybf6CMGEnLT1yEfqpxeDNs9nWN1m1s/Bgpv/sxXA6ehQ1FV3NiXLXxKuWHkKtPuwMJCGmWdjJqOuVAqjc/0mz6e0mNF992vhOby9Xj4i04asK/F89m8kofo5zGliPx75A7AzXkQUtzbs7mgRygIem0GiFQJRezyX2YnfHJzq57UihAF6PrYqln/Tz7MJ50uDKea8kLGOL/Mef/8h9FcfrQ3OHhaGmjuqO3aOpENUzs6xdJwQuU/HDY61siPKMJNt4gnZKo2ZSxVdLMT/w8vpUVGqgLuYfWZndDRJgFqCSyp8nEaXe0SVvtbVGQPBgoBRCkmkeNE0WTobULRynkNYpMbGStlwNUgNLecbx7hF8HOwaYcQAFQPREMwEhjiylxEBokbzJAFgtp74IPuX/wbZ9fYocryDOxF4U2fYjXMOGY7enhqS7+r0fG56jfi38sYuCIBgmUT3QvlN2soxwomCjO1G/z1cvhwbA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Risk
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
