env:
  global:
    - secure: WOP/3jWJ7ICYO2tXPRh0F0a5AkS9IEphw1XmA4ff0QSfbjKAPH3WWi7Pwt6PcUHaz9NmRVOh8QRAcdahAZKOWYqXvAM8FtNvxxpBQDuQfLQgiCNPBInx7hNeibvU6yrZzuYEH3AzLl3/Gw39aQ1boTnTR4oW3NHwgkwSg1E3xNlvEUjQSHx0VAc1rzqjninPqnN0YxI7N3QYPUVtAl+0/4llfiDhWsL4ecv2BxNr/BbIyciKFGdFKy1pzqvItRuKjOQNDIb1hGn8uqVFr/0vBgPp2AjT1LgG1sEaOk+Cu4ygDKsFzHN/fBRS5KQ3wjYTNuR8tzoEMVuQN5W3n65v8PbjzMDXfFWe4PW8rbt78wy7wAJznuO+actBK+QnSTys18qBrvOLkB/ev41NstsXPgnq0sO+9vVBbamqA99CoOdwdxaNrI+Bc0lVVRdQOhI1d/hgFU2EnMCB4q3sqcHd8Q0JQKfBENnQG1R/8uW4WSSJN2CF2rilvFkKvbxkaFnben1x/DLbCGHRHARA5hBeZaxIIEpQps4UCH7qzIVsbB7WdIDid3xsCTHnRzyVgvsdmMF3g3Ka9xyJ6nWuu4F02LBgeWeywnpZuuK0rEyyZOsTb8jNLj5qQ0FxUD5Nw/6m9yUGZTFRNH8Fh/lXw9jq7EltIS64hMNLxcHOvmGgyp0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Risk
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
