env:
  global:
    - secure: JtX43rDLWojs5xr26FjztOO5rKpE32Q3U3o8CvluE2trJ4RC699ARIXXcuCR5M+yTxOc0HTGmq6pr3fVwL7s/bbdoVyaCr/jGsNbcgM1SY9t6UA0fIkrugkIBpiq6dc+BsosaNpMCH6wz29y6WSIwMGX89d7lUJaIkKSC7TthUzuRDer103qOzc/fbyfTid3r4uxg5S43u47mxU7Mbk4ThEytMQmidAk7Bd4oxYZ1Sj/01Zd9I8ZKSZl9sPhYTqw1eBGidkewwq+40cBbgc43C3rGLOb1U+hVYETgLMoPbmXrnPmOkPcybJoFZGzk8WzjyPbPabEA3OvVpEApgMHZmQmBv5pZWYYJQz83wNO8tY+j+4O+kzfnqHDabaRWXnib5W1l93VlvqlG2/shdSDfvgVnHyhRaKLlcN4XBWcummyN6mGvPeBqgV18Agc3eI/GDC4pauwfIVu4wzwDK/kMCq635ESAdrPSPGof7HlKPmSuj4yVg0guUQW3j3dvYWKOdoFyqPh4ICJM73vfV2PxCS8KYZgQSGWA+WSZtyx8FzhRDX712yY2RuU+tTysJviVa95AIAT8zX+DGSfzOtVKJG8fRPtXzwuMV5BPXJRT+0/zmp86nq/qlc7uZXNJsKYn5pUdwtmOVqY1mnAG9eP5RCHzLDjEjj7mKs0jprKxeE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Risk
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
