env:
  global:
    - secure: gxGUoq1BBUACk2x/elIPpG766pPJQ/GtKeeCVKRZ1C8+U/Ut3uGeziWsH2ty81M5zE9yP+GUUeH3O7ky8Vnle6wucHjeC7m0Hbz20SiBrtiBaNxXDIvsVFTdMeQmvQKFekA9YZcoVw+Zp8mM2UCOejc/zuHPSX+fc0hWK21RrUYkOnyVYwrJ6BvlBMukhaJNHQK/BXQp+KNY0KucItSWUt9AzGQV401BgkeEuH3RYX9Vu0JDn44oqumFz8PmlkeSDjSKNZtWzZRN+bir3JeWIlppXpCzpwC0gKBf31dS2xcp3IFFHe7aZjH1eT73MAWsXA08+D8mLkata6Atx8I8ohT46nagqurPWpiuM4WoFsfLDXWAAtn3Vd0R5ZO2bNEc1rcr6OfZpNwvCLAO+WzWkvnR60SjEfKsLznbn7p8iuMCrrz2SuiEpSMb6+pdmj+ToOTYh/CSZr4aLymONzMbCkPo3gpqUK+NvLD+OQnwid64rEoI/o0EmIafn/MdArCR6GnzOTwJeBRjpJzijGFLzkMFUsddMxkAVTe9+1cI7valX3i51iprsDoUT/Pv0TsEXt22mHbt1lM1ZdEsqObcVv0E6aI7neAxD42Vx55XWLyBBTzvznqRmEE271cV1uZcEmA3snhBgpkDVauhI6zQHBRcORxOgKiaPyuj8Rzarg0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Risk
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
